---
- name: cf_space module examples
  hosts: cfclient
  gather_facts: false

  tasks:
    - name: create space stest in test org
      cf_space:
        name: "stest"
        organization: "test"
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: create space stest in test org (again)
      cf_space:
        name: "stest"
        organization: "test"
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: delete space stest
      cf_space:
        name: "stest"
        organization: "test"
        state: absent
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: delete space stest (again)
      cf_space:
        name: "stest"
        organization: "test"
        state: absent
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: create space test in test org
      cf_space:
        name: "test"
        organization: "test"
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

# Warning! In order to add an user as [manager, auditor]
# first they have to be added as a user!, otherwise the error:
# CF-InvalidRelation (1002) will appear

    - name: create user bob (if he not exists)
      cf_user:
        name: "bob"
        password: "hola"
        email: "bob@hola.com"
        given_name: "Bob"
        family_name: "SpongeBob"
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: create org test2
      cf_org:
        name: "test2"
        quota: "default"
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: add user bob to stest2 in test2 org
      cf_space:
        name: "stest2"
        organization: "test2"
        user_name: "bob"
        user_role: user
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: promote bob as manager in the test2 org space stest2
      cf_space:
        name: "stest2"
        organization: "test2"
        user_name: "bob"
        user_role: manager
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: demote bob as user in the test2 org space stest2
      cf_space:
        name: "stest2"
        organization: "test2"
        user_name: "bob"
        user_role: manager
        user_state: absent
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: delete org test2 with force (there are spaces there!)
      cf_org:
        name: "test2"
        quota: "default"
        state: absent
        force: true
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"

    - name: delete user bob
      cf_user:
        name: "bob"
        state: absent
        admin_user: "{{ cf_admin_user }}"
        admin_password: "{{ cf_admin_password }}"
        api_url: "{{ cf_api }}"
