---
# Quotas

- name: "Quotas - Processing quota definitions"
  cf_quota:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    non_basic_services_allowed: "{{ item.non_basic_services_allowed | default(true) | ternary('yes', 'no') }}"
    total_services: "{{ item.total_services }}"
    total_routes: "{{ item.total_routes }}"
    memory_limit: "{{ item.memory_limit }}"
    instance_memory_limit: "{{ item.instance_memory_limit | default(-1) }}"
    total_service_keys: "{{ item.total_service_keys | default(omit) }}"
    total_reserved_route_ports: "{{ item.total_reserved_route_ports | default(omit) }}"
    total_private_domains: "{{ item.total_private_domains | default(omit) }}"
    app_instance_limit: "{{ item.app_instance_limit | default(omit) }}"
    admin_user: "{{ cf_admin_user }}"
    admin_password: "{{ cf_admin_password }}"
    api_url: "{{ cf_api }}"
  with_items: "{{ cf_quotas | default([]) }}"

